name: app-test

on:
  pull_request:
    branches: [ "main", "dev" ]

defaults:
  run:
    working-directory: ./TestWrite-app

jobs:
  start-server:
    runs-on: ubuntu-latest
    environment: Test
    env:
      working-directory: ./TestWrite-api

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Migrate database
        env:
          DB_CONNECTION: sqlite
        run: php artisan migrate:fresh --seed
      - name: Start server
        run: php artisan serve

  test:
    runs-on: ubuntu-latest
    needs: start-server
    environment: Test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run lint
          npm test
